### ISSUE TITLE
Sometimes Lambda Coverage is calculated differently

### ISSUE THREAD

**Issue by mustafaozhan** [Kotlin/kotlinx-kover#275] opened 2022-11-12 13:04 UTC
Please check the attached picture, the coverage changes in the picture happens time to time, I couldn't find any logical reason.
Please note that nothing on the lines are actually changed.

Here is the PR (just dependency updates): https://github.com/Oztechan/CCC/pull/1299
Here are the Coverage changes in mentioned PR:
<img width="1056" alt="Screenshot 2022-11-12 at 16 01 08" src="https://user-images.githubusercontent.com/30001999/201475203-558c2692-5de4-482e-8249-1ada7181ce1f.png">

**Environment**
 - Kover Gradle Plugin version: 0.6.1
 - Gradle version: 7.5.1
 - Kotlin project type: Kotlin/Multiplatform

**Comment by zuevmaxim** [comment] 2022-12-13 15:08
Difference in coverage reports could be caused by Kotlin plugin update. @mustafaozhan Does the issue reproduce in case when the code and global set up do not change?

**Comment by mustafaozhan** [comment] 2022-12-13 15:20
@zuevmaxim yes, I would say 70% percent of my PRs are having the same coverage change.

Meanwhile, sorry I forgot when I create the issue, I think it will be valuable to add, mentioned methods `Logger.v` and `Logger.d` methods are `inline` I suspect on this.

**Comment by zuevmaxim** [comment] 2022-12-14 17:27
@mustafaozhan Looks like the issue has been already fixed in agent version `1.0.691`

In lines you provided, there is a boolean converted to string. Internally, it is converted into a bytecode
```
       104: iload_3
       105: ifeq          112 // EXTRA BRANCH HERE
       108: iconst_1
       109: goto          113
       112: iconst_0
       113: invokevirtual #103    // Method java/lang/StringBuilder.append:(Z)Ljava/lang/StringBuilder;
```
I suppose that this boolean value may somehow differ in your tests.
In the latest version of the coverage engine, this branch is ignored.

To use custom engine you need to configure it in all projects where Kover is used
```
kover {
    engine.set(kotlinx.kover.api.IntellijEngine("1.0.691"))
}
```

**Comment by mustafaozhan** [comment] 2022-12-23 08:53
@zuevmaxim thank you for the suggestion, I will try it on the other hand I have question about the `engine` is it something that you guys update in each release ? I am asking because it looks like I will need to revert this changes at some certain point.

Is there any place where I can check with Kover version uses which engine version ?

**Comment by zuevmaxim** [comment] 2022-12-26 10:56
@mustafaozhan Yes, engine version can be updated with new versions of Kover. Usually it is the most recent version of the engine used, so with the new version of Kover you will not need this set up (and possibly it will not be allowed as Kover can update the minimal compatible version). 

As for the engine version, you can find the default used version in https://github.com/Kotlin/kotlinx-kover/blob/v0.6.1/src/main/kotlin/kotlinx/kover/api/KoverConstants.kt Change the tag to see the default engine version for other versions of Kover

**Comment by mustafaozhan** [comment] 2022-12-26 20:45
Okay thanks a lot @zuevmaxim!, I think we can close this issue now, if it will occur again I will open it back 🙂

**Closed** 2023-02-23 19:56 UTC
Labels: Bug, IntelliJ Coverage Engine, S: untriaged
