### ISSUE TITLE
Getter and Setter of `data` class should not be cover or need new parameter for unchecked them.

### ISSUE THREAD

**Issue by tmdgusya** [Kotlin/kotlinx-kover#417] opened 2023-06-27 05:57 UTC
**What is your use-case and why do you need this feature?**
I was wondering why it covers `data class properties(Getter and Setter are created by Compiler)`. 
Because, There is no method for specific behavior usually and they just only contain data.

Related to: https://github.com/Kotlin/kotlinx-kover/issues/174

**Describe the solution you'd like**
This is a simple way to think about it
```yaml
cover:
  contain-data-class-coverage: true
```

**Comment by shanshin** [comment] 2023-06-27 07:11
Hi,
the desired goal pursued by Kover is to search for any code that is written by a developer, but for some reason has not been used properly.
The motivation of Kover 's behavior is as follows: if some code is written but has not been used, then either such code should be deleted or excluded by a specific domain, for example, by the package name, if only one of the many tests is run that does not check the specified package.
Excluding all data classes from the project in this case looks redundant, because in this case, Kover stops looking for unused code, which can mask problems in whole application due to one unused data class, or data classes of some business domain.

So that we can understand how best to solve your problem, could you describe your use case, for what reason there are data classes in the project that are not used, but cannot be removed from the project?

**Comment by tmdgusya** [comment] 2023-06-29 02:54
@shanshin 
I understood that. but, I have a question. One of the **main feature** is "**Collection of code coverage through JVM tests**", so I think you're keeping to support this feature(**test coverage**), In my opinion, I think this library should have a "**exclude feature that I've mentioned**" or separate module like a "test-kover".

**Comment by tmdgusya** [comment] 2023-06-29 02:56
@shanshin 
Sometime, I think I don't need to test properties that just automatically made by compiler. Have you ever test methods by created by lombok(`@getter/@setter`) when you was using java

**Comment by tmdgusya** [comment] 2023-06-29 03:00
@shanshin 
I totally agree with that If I write a method in `data` class, those methods should be tested and must be covered. But, I don't think that I need to test methods in `data` class that created by Compiler or Annotation Processor. Some think we should test all of method or properties in `data` class. So, I think we should make the "parameter", and We can turn off and turn on, If you think don't need to test those properties in `data` class

**Comment by shanshin** [comment] 2023-06-29 12:09
At the moment, for data classes, the coverage of getters and setters should not be measured.

An example of a data class for which getter or setter coverage is measured would be very useful. An example of a coverage report of this class will also help.

**Comment by shanshin** [comment] 2023-07-12 08:59
Most likely a duplicate #420.

if you have a reproducer project, it would be very helpful to understand the problem of why sometimes properties are marked as uncovered.

**Closed by shanshin** 2023-07-12 08:59 UTC
Labels: Feature, S: waiting for clarification
