### ISSUE TITLE
Unit tests randomly failing just after enabling kover plugin in the project

### ISSUE THREAD

**Issue by radimjanda754** [Kotlin/kotlinx-kover#360] opened 2023-05-03 16:29 UTC
**Describe the bug**
Just after adding kover to the project

`classpath("org.jetbrains.kotlinx:kover:${PluginVersions.kover}")`

`apply plugin: 'kover'`

the unit tests randomly start to fail (however they run without any failures without kover in the project). I even tried disabling failing tests, but just more and more random fails keep appearing.

We use classic kotlin.test.Test tests and some libs to help with testing (io.mockk.mockk).

Any idea what could cause this?

**Errors**
Randomly failing unit tests

**Expected behavior**
Test results would be same as if kover plugin is not enabled.

**Environment**
 - Kover Gradle Plugin version: 0.6.1
 - Gradle version: 7.4.2
 - Kotlin project type: Kotlin/Android, Kotlin/Multiplatform

**Comment by shanshin** [comment] 2023-05-05 11:06
Hi,
could you show an example of errors and stacktraces with which tests fall?

Do you use okhttp in your tests?

**Comment by radimjanda754** [comment] 2023-05-15 12:53
Hello, seems all stacktraces looks like this:

`java.lang.IllegalArgumentException: Unsupported class file major version 61
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:196)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:177)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:163)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3824)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3595)
	at io.mockk.proxy.jvm.transformation.InliningClassTransformer.transform(InliningClassTransformer.kt:78)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation$execute$1.invoke(RetransformInlineInstrumnetation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation$execute$1.invoke(RetransformInlineInstrumnetation.kt:6)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation.execute(RetransformInlineInstrumnetation.kt:16)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
	at io.mockk.impl.instantiation.AbstractMockFactory.temporaryMock(AbstractMockFactory.kt:127)
	at io.mockk.impl.recording.states.RecordingState$call$retValue$1.invoke(RecordingState.kt:72)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$2.invoke(JvmAnyValueGenerator.kt:35)
	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:34)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:31)
	at io.mockk.impl.recording.states.RecordingState.call(RecordingState.kt:70)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
`

**Comment by radimjanda754** [comment] 2023-05-18 11:22
@shanshin 
Tried updating kover to 0.7.0 and mock libraries to latest version, problem still persist.
We have okhttp3 in some parts of code, on some tests we use com.squareup.okhttp3:mockwebserver. But even more simple tests that shouldn't use these libs are crashing.

**Comment by shanshin** [comment] 2023-06-01 15:07
Please try version `0.7.1` - is bug reproduced in it?

**Comment by radimjanda754** [comment] 2023-06-04 21:50
Still problems even on 0.7.1 just I got different exception,

Steps to reproduce:
Removed kover from the project completly, run ./gradlew testXyzDebugUnitTest - all tests successful

Added just basic kover configuration to the project apply plugin: 'org.jetbrains.kotlinx.kover' , run  ./gradlew testXyzDebugUnitTest - several tests failed

The exception now shows as timeout:

```
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at ???(Coroutine boundary.?(?)
	at kotlinx.coroutines.channels.AbstractChannel.receiveCatching-JP2dKIU(AbstractChannel.kt:633)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:51)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invokeSuspend(ChannelFlow.kt:123)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:26)
```

**Comment by shanshin** [comment] 2023-06-27 16:09
@radimjanda754 , do the same errors happen in `0.7.2`?

**Comment by shanshin** [comment] 2023-08-15 08:41
I'm closing the issue for now.

Feel free to open new issue if the problem is reproduced again. 
In this case a small reproducer project or more information about the environment will be useful.

**Closed by shanshin** 2023-08-15 08:41 UTC
Labels: Bug, S: waiting for clarification
