### ISSUE TITLE
Convention plugin + filtering projects

### ISSUE THREAD

**Issue by igorromcy** [Kotlin/kotlinx-kover#582] opened 2024-03-25 17:23 UTC
Hey there! 

I'm wondering how I should use kover for this case: 

I need to configure kover using my convention plugin because I want to run using a filtered list of projects.
But looks like we need to configure the main build.gradle file anyway, so I'm not sure how we can avoid configuration conflicts there, is there any default configuration we can leave there to merge all the reports generated by my convention plugin kover configuration? 

this is how I'm using it so far, but I think allProjects won't work the way I need
 
```
kover {
    merge {
        allProjects()
        createVariant("coverage") {
            it.addWithDependencies(["fastDebug", "debug"] as String[], true)
        }
    }
}
```

**Comment by shanshin** [comment] 2024-03-25 17:30
Hi,
you would like the names of the projects in which you want to apply Kover to be specified in the applied project? Or how do you want to filter projects?

**Comment by igorromcy** [comment] 2024-03-25 17:37
I want to filter like you said last week 

```
kover {
    merge {
        allProjects {
            it.path in setOf(":feature:login", ":feature:signup") // or for Groovy  [":feature:login", ":feature:signup"]
        }
    }
}
```

but the problem is that I still need to configure the main build.gradle file anyway, so I can merge all the filtered projects

**Comment by shanshin** [comment] 2024-03-25 20:58
``` kover { merge { ... ``` DSL it was designed just so that there was no need to create a convention plugin for Kover, and all the settings needed to be specified in only one project.

If, for some reason, it becomes necessary to use a convention plugin, then it is enough to create an project extension to configure this convention plugin.
Like this:
Convention Plugin
```
interface KoverSettings {
    val projects: ListProperty<String>
}

val settingsExtension = extensions.create<KoverSettings>("koverSettings")

kover {
    merge {
        allProjects {
            it.path in settingsExtension.projects.get()
        }
    }
}
```

Project kts
```
extensions.configure<My_plugin_gradle.KoverSettings> {
    projects.addAll(":feature:login", ":feature:signup")
}
```

Project Groovy
```
koverSettings {
    projects.addAll(":feature:login", ":feature:signup")
}
```
*name `My_plugin_gradle` will be different for you and depends on the name of the convention plugin
** it is strictly not recommended to put the configuring of `KoverSettings` extension in the `afterEvaluate` block

**Comment by igorromcy** [comment] 2024-03-27 17:24
that's great, I could make it works via convention plugin! 

I'm now curious about this scenario: I have 2 shards running for example 50 and 100 modules respectively (2 different steps on pipeline) 

Is it possible with kover to merge the reports after both executions? 

I was trying to do that via the root build.gradle file + convention plugin, but it seems that we have conflicts, is that right?

**Comment by igorromcy** [comment] 2024-03-27 19:14
In other words, I want to merge all the projects which has coverage file generated (on the main build.gradle file)

**Comment by shanshin** [comment] 2024-03-28 12:55
I think you may close this issue and track [this](https://github.com/Kotlin/kotlinx-kover/issues/585), because there will be a discussion of the same question.

**Closed** 2024-03-28 14:30 UTC
Labels: Question, S: in progress
