### ISSUE TITLE
gradle configuration cache support in 0.6.0-Beta

### ISSUE THREAD

**Issue by Chrisjc28** [Kotlin/kotlinx-kover#203] opened 2022-08-09 14:57 UTC
It seems when targeting version 0.6.0-Beta and enabling gradle caching,  there is a problem when running the kover html report task it finds a large amount of problems storing the configuration cache.

Example message from project- 
```
5169 problems were found storing the configuration cache, only the first 4096 were considered, 31 of which seem unique.
```

Just raising this as it might be something that needs to be looked into to for people who use gradle caching

**Comment by shanshin** [comment] 2022-08-09 15:02
Relates #144

**Comment by shanshin** [comment] 2022-10-27 15:23
Closed as a duplicate of #144

**Closed by shanshin** 2022-10-27 15:23 UTC
Labels: Kover Gradle Plugin, Feature
