### ISSUE TITLE
Allow/fix aggregation `includedBuild`s

### ISSUE THREAD

**Issue by gmazzo** [Kotlin/kotlinx-kover#598] opened 2024-04-18 13:14 UTC
**What is your use-case and why do you need this feature?**
`kover` integrates with Gradle's dependency resolution system by exposing a `kover` configuration to aggregate projects 

As `includedBuild`s by convention exposes a dependency coordinate (implicit `dependencySubstitution`), declaring it as a `kover` dependency is expected to aggregate the child build into the main report.

```kotlin
dependencies {
    kover(":build-logic")
}
```

This setup does not break the build, the correct `koverArtifact[TOTAL]` variant is resolved for the included build, but the report does not aggregate it.
![image](https://github.com/Kotlin/kotlinx-kover/assets/513566/ace4a9f6-a52f-4710-afe0-c7551f5012b7)
https://scans.gradle.com/s/2nb3nedv4ntsm/dependencies?focusedDependency=WzAsMCwyLFswLDAsWzJdXV0&toggled=W1swXSxbMCwwXV0

Running `./gradlew :koverHtmlReport` produces a report only containing main build modules:
![image](https://github.com/Kotlin/kotlinx-kover/assets/513566/62770681-1295-42cd-8577-1b0f86d27f0e)

While running `./gradlew :build-logic:koverHtmlReport`, is correctly computing the `build-logic` modules (some now not aggregated in the root one):
![image](https://github.com/Kotlin/kotlinx-kover/assets/513566/0915f2c4-0680-4dbc-833b-2a6984d0bb23)

**Describe the solution you'd like**
Included Builds should be transparently resolved as any other `kover` dependency and included in the aggregated report. Variants are there, it's seems to a matter of the internal plugin resolution strategy.

> [!IMPORTANT]
> I provided a sample project at https://github.com/gmazzo/kover-demo-aggregation-issue/?tab=readme-ov-file#includedbuilds-not-aggregating

**Comment by shanshin** [comment] 2024-04-23 22:05
Unfortunately, Composite Builds are not supported at the moment, there are a number of technical limitations why it does not work in its current form.

**Comment by shanshin** [comment] 2024-04-23 22:07
A [task](https://github.com/Kotlin/kotlinx-kover/issues/487) has already been opened to design support for such types of builds.

**Comment by shanshin** [comment] 2024-04-23 22:08
Closed as a duplicate of https://github.com/Kotlin/kotlinx-kover/issues/487

**Closed by shanshin** 2024-04-23 22:08 UTC
Labels: Feature, S: untriaged
