### ISSUE TITLE
NPE after update from 0.6.0 to 0.6.1

### ISSUE THREAD

**Issue by BobrD** [Kotlin/kotlinx-kover#335] opened 2023-04-06 15:27 UTC
### Errors
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.intellij.rt.coverage.data.instructions.ClassInstructions.getlines()" because "classInstructions" is null
	at com.intellij.rt.coverage.util.InstructionsSection.saveClass(InstructionsSection.java:96)
	at com.intellij.rt.coverage.util.ClassListSection$1.execute(ClassListSection.java:51)
	at com.intellij.rt.coverage.util.ClassListSection$1.execute(ClassListSection.java:48)
	at org.jetbrains.coverage.gnu.trove.TObjectIntHashMap.forEachEntry(TObjectIntHashMap.java:379)
	at com.intellij.rt.coverage.util.ClassListSection.saveInternal(ClassListSection.java:48)
	at com.intellij.rt.coverage.util.ReportSection.save(ReportSection.java:61)
	at com.intellij.rt.coverage.util.ReportSectionsUtil.saveSections(ReportSectionsUtil.java:74)
	at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:103)
	at com.intellij.rt.coverage.aggregate.Aggregator.processRequests(Aggregator.java:98)
	at com.intellij.rt.coverage.aggregate.Main.main(Main.java:27)
	
```

Environment

Kover Gradle Plugin version: 0.6.1
Gradle version: 7.6
Kotlin: 1.8.10
Kotlin project type: Kotlin

**Comment by shanshin** [comment] 2023-04-11 13:33
Hi, 
It looks like it's a duplicate of #296, try the fix specified there.

**Comment by shanshin** [comment] 2023-04-21 16:42
Feel free to open new bug issue if the problem reproduced again.

**Closed by shanshin** 2023-04-21 16:42 UTC
Labels: Bug, S: waiting for clarification
