### ISSUE TITLE
with `onCheck.set(true)` merged tasks are not launched 

### ISSUE THREAD

**Issue by AleksDanil** [Kotlin/kotlinx-kover#213] opened 2022-08-18 20:42 UTC
0.6.0-Beta

I configured simple multi module project and set `onCheck.set(true)` for `verify`, `htmlReport`, `xmlReport` inside `koverMerged` for parent module:
```kotlin
koverMerged {
    enable()

    xmlReport {
        onCheck.set(true)
    }
    
    htmlReport {
        onCheck.set(true)
    }

    verify {
        onCheck.set(true)
        ...
    }

}
```
None of koverMergedHtmlReport, koverMergedXmlReport, koverMergeVerify is launched when I run check task.

You can check attached project [MultiModule.zip](https://github.com/Kotlin/kotlinx-kover/files/9377495/MultiModule.zip)

**Comment by shanshin** [comment] 2022-08-19 13:09
Not a bug, lack of documentation:
`onCheck` applies only to the `check` task located in the same project where the merged tasks were created (`koverMerged.enable()` was called).

In this example, this is the root project. However, because the [base plugin](https://docs.gradle.org/current/userguide/base_plugin.html ) is not directly or transitively applied , then the check task does not exist in it and merged reports are not attached to anything.

This is easy to check by calling `./gradlew :check`.

**Closed** 2022-08-23 13:32 UTC
Labels: documentation
