### ISSUE TITLE
CLI for kover

### ISSUE THREAD

**Issue by Vacxe** [Kotlin/kotlinx-kover#238] opened 2022-09-19 06:17 UTC
Does Kover have a CLI [similar with JaCoCo ](https://www.jacoco.org/jacoco/trunk/doc/cli.html) ?

I using JaCoCo to visualise coverage for UI tests. On `assemble` stage I preparing all `.class` files and then UI tests sharded with Marathon on two agents. As an aggregation I have `.class`s files and `.ec`s from devices. And then I can generate total coverage from those artifacts with CLI.

Is it possible to have the same functionality with this library?

**Comment by shanshin** [comment] 2022-09-19 10:03
Hi,
at the moment there are no CLI tools in Kover

**Comment by shanshin** [comment] 2023-03-17 12:45
Closed as a duplicate of #322

**Closed by shanshin** 2023-03-17 12:45 UTC
Labels: Kover Coverage Tool, Feature, Design needed, S: postponed
