### ISSUE TITLE
Encoding of <init> within XML report has changed between 0.6.x and 0.7.2

### ISSUE THREAD

**Issue by quanturium** [Kotlin/kotlinx-kover#442] opened 2023-07-27 19:36 UTC
**Describe the bug**
The ">" is not properly encoded in the XML report after 0.7.2 migration from 0.6.x. 

Before:

```
<method name="&lt;init&gt;" desc="()V">
<counter type="INSTRUCTION" missed="2" covered="0"/>
<counter type="BRANCH" missed="0" covered="0"/>
<counter type="LINE" missed="1" covered="0"/>
</method>
```

After:

```
<method name="&lt;init>" desc="()V">
<counter type="INSTRUCTION" missed="2" covered="0"/>
<counter type="BRANCH" missed="0" covered="0"/>
<counter type="LINE" missed="1" covered="0"/>
</method>
```

^ Notice the ">" that is no longer converted to &gt;

**Comment by shanshin** [comment] 2023-07-27 20:08
Hi,
could you please provide a reproducer?
Is this reproduced on all classes? What is the local encoding used, Gradle and Kover version?

**Comment by shanshin** [comment] 2023-07-27 20:23
Is the problem reproducible in `0.7.3` version?

**Comment by quanturium** [comment] 2023-07-27 22:12
> could you please provide a reproducer?
> Is this reproduced on all classes? What is the local encoding used, Gradle version?

You'll find this reproduces on any classes that has a constructor. XML file generated is in UTF-8. 

```
❯ ./gradlew --version                                                                                                                   

------------------------------------------------------------
Gradle 8.2-rc-1
------------------------------------------------------------

Build time:   2023-05-31 18:12:05 UTC
Revision:     2a2778f51363d9574f808ae80d34d8b5bd99d98b

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.7 (Azul Systems, Inc. 17.0.7+7-LTS)
OS:           Mac OS X 13.4.1 aarch64
```

> Is the problem reproducible in 0.7.3 version?

Just tried it out since I had missed the 0.7.3 release and it does reproduce as well.

**Comment by shanshin** [comment] 2023-07-28 10:03
> You'll find this reproduces on any classes that has a constructor.

Unable to reproduce in different versions of Gradle including `8.2.1`.

**Comment by shanshin** [comment] 2023-08-15 08:05
@quanturium, did you manage to create a small producer?
This was not reproduced on our build machines.

**Comment by shanshin** [comment] 2023-10-27 13:43
Closed as non-reproducible.
Please, if you manage to reproduce the problem on a small project, reopen the issue and attach this example.

**Closed** 2023-10-27 13:43 UTC
Labels: Bug, S: waiting for clarification
