### ISSUE TITLE
Excluding classes with Wildcard doesn't work

### ISSUE THREAD

**Issue by mustafaozhan** [Kotlin/kotlinx-kover#252] opened 2022-10-05 22:35 UTC
Hello 👋 

I tried to exclude my test classes from the reports by adding below code
```kotlin
koverMerged {
    enable()
    filters {
        classes {
            excludes += listOf(
                "*Test",
                "*.*Test",
                "*.*.*Test",
                "*.*.*.*Test",
                "*.*.*.*.*Test"
            )
        }
    }
}
```
it doesn't seem working, i can still see my classes ending with `...Test` in the coverage report

**Comment by shanshin** [comment] 2023-02-27 18:33
Try `0.7.0-Alpha` version.

Perhaps there may be problems with migration due to incomplete documentation.
In addition to the changed DSL, the approach to creating merged reports has changed, now you need to specify the `kover` dependency to create them.

**Comment by shanshin** [comment] 2023-04-21 17:14
Please try the new DSL in version `0.7.0-Beta'.
Feel free to open new bug issue if the problem reproduced again.

**Closed by shanshin** 2023-04-21 17:14 UTC
Labels: Bug, S: untriaged
