### ISSUE TITLE
gradlew koverHtmlReport koverVerify launches "Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by skyviolantea** [Kotlin/kotlinx-kover#183] opened 2022-05-24 12:15 UTC
Hi,

When I try to run "gradlew koverHtmlReport koverVerify" to generate a report, I receive the following error. It seems something has changed in my application that generates an error as some commits ago I was able to do it without encountering problems. Now it happens and I don't understand where to find the problem or how can I debug this.

[ERROR] [system.err] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
[ERROR] [system.err]       at jetbrains.coverage.report.idea.IDEACoverageClassInfo.getStatementStats(IDEACoverageClassInfo.java:129)
[ERROR] [system.err]       at jetbrains.coverage.report.impl.StatisticsCalculatorImpl.computeForClass(StatisticsCalculatorImpl.java:51)
[ERROR] [system.err]       at jetbrains.coverage.report.impl.StatisticsCalculatorImpl.doCompute(StatisticsCalculatorImpl.java:40)
[ERROR] [system.err]       at jetbrains.coverage.report.impl.StatisticsCalculatorImpl.compute(StatisticsCalculatorImpl.java:34)
[ERROR] [system.err]       at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:80)
[ERROR] [system.err]       at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:76)
[ERROR] [system.err]       at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:53)
[ERROR] [system.err]       at com.intellij.rt.coverage.report.Main.main(Main.java:48)
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Program Files\Java\jdk11015\bin\java.exe'' finished with exit value 1 (state: FAILED)

Can you help me to understand what should I check and what should I do to solve the problem?

Thanks a lot!

**Comment by shanshin** [comment] 2022-05-24 13:57
Hi,
is your project open source?

**Comment by shanshin** [comment] 2022-05-24 13:58
Related #166

**Comment by k3marek** [comment] 2022-06-02 21:50
I've experienced same issue; in my case with android modules. Switching to `intellijEngineVersion.set('1.0.671')` solved it

**Comment by chris-hatton** [comment] 2022-06-18 05:05
Seeing the same issue with engine `10.0.668`, but only when run on our Linux CI machine.  The same task locally on an M1 Mac succeeds.

**Comment by saschpe** [comment] 2022-07-13 09:56
Same here using Cover `0.5.1` on Apple M1. Setting `intellijEngineVersion.set("1.0.674")` fixed it as well.

**Comment by aSemy** [comment] 2022-07-26 17:10
You can get the latest IntelliJ engine version from looking at the versions in Maven Central: https://search.maven.org/artifact/org.jetbrains.intellij.deps/intellij-coverage-agent

**Comment by iptton** [comment] 2022-08-03 07:44
@shanshin I think that's because I got some ignored test method

**Comment by shanshin** [comment] 2022-08-23 18:19
Must be fixed in `0.6.0`, feel free to reopen if the problem reproduced again.

**Closed by shanshin** 2022-08-23 18:19 UTC
Labels: Bug, IntelliJ Engine
