### ISSUE TITLE
What is proper way to get parseable coverage rate for badge in CI (gitlab) 

### ISSUE THREAD

**Issue by comdiv** [Kotlin/kotlinx-kover#167] opened 2022-04-15 06:12 UTC
Please add options to enable ConsoleReporting for Coverage  - to allow parsing them for Coverage Badge in gitlab

**Comment by sschuberth** [comment] 2022-04-15 07:31
This sounds like a duplicate of https://github.com/Kotlin/kotlinx-kover/issues/155.

**Comment by comdiv** [comment] 2022-04-15 07:33
duplicate

**Closed** 2022-04-15 07:32 UTC
