### ISSUE TITLE
Kover not working with robolectric

### ISSUE THREAD

**Issue by fpitpit** [Kotlin/kotlinx-kover#181] opened 2022-05-16 18:03 UTC
the report indicates no tests when launch tests with robolectric
I've got an empty report

Could you put a sample app multi modules with unit tests robolectric that tests for several android versions  else i will return to user jacoco

**Comment by shanshin** [comment] 2022-05-19 10:57
Hi,
at the moment, the Kover does not support instrumentation of tests performed on the Android device.
If you have exactly such tests, then you can use JaCoCo for them until support for Android devices is added to Kover.

**Comment by shanshin** [comment] 2022-05-19 10:59
Duplicated #96

**Comment by adrianwitaszak** [comment] 2022-08-18 12:11
Is there any rough estimate of support for instrumentation tests in Android?

**Comment by shanshin** [comment] 2022-08-23 18:30
@adrianwitaszak, in the near future we will begin to study ways of instrumentation of Android devices and I think soon after that we will be able to report approximate implementation dates.

**Comment by shanshin** [comment] 2022-08-23 18:31
Closed as a duplicate of #96

**Closed by shanshin** 2022-08-23 18:31 UTC
Labels: IntelliJ Engine, Feature
